### ISSUE TITLE
project.excludeFilters no longer respected

### ISSUE THREAD

**Issue by hseeberger** [lucidsoftware/neo-sbt-scalafmt#17]
After upgrading from 1.3 to 1.6 `project.excludeFilters` is no longer respected. I'm using 
```
project.excludeFilters     = [".*\\.sbt"]
```
to **not** format my .sbt files, but with 1.6 these are formatted nevertheless.

**Comment by olafurpg** [comment]
FWIW, `ScalafmtConfig.project.matcher.matches(path): Boolean` can be used to check if a file is supposed to be formatted or not, see https://github.com/scalameta/scalafmt/blob/d204ae1437247aae0f0b8a9901e433368057e678/scalafmt-core/shared/src/main/scala/org/scalafmt/config/ProjectFiles.scala#L13

**Comment by pauldraper** [comment]
It never respected `project.excludeFilters`, rather using SBT's `excludeFilter`. I'm not sure which is the right thing to support.

---

In any case, the 1.3->1.6 difference is that .sbt files are now supported.

If you have `scalafmtOnCompile` enabled, you will need to disable it for the `sbt` config.

```
scalafmtOnCompile in Sbt := false
```

**Comment by pauldraper** [comment]
Good to know about ScalafmtConfig's match @olafurpg . That's an easy inferface. sbt-scalafmt should use that.

**Comment by olafurpg** [comment]
The exclude/include filters name in that setting is borrowed from sbt. It
should behave similarly, otherwise it's a bug. The problem with sbt
settings is that it's difficult to extract them from the scalafmt cli and
IntelliJ plugin.
