### ISSUE TITLE
Adding the Coursier plugin doesn't seem to enable Coursier?

### ISSUE THREAD

**Issue by lloydmeta** [lucidsoftware/neo-sbt-scalafmt#24]
Even though I've added the companion coursier plugin, SBT doesn't download un-cached dependencies using Coursier's downloader.

I added the plugin to my project via 

```scala
addSbtPlugin("com.lucidchart" % "sbt-scalafmt-coursier" % "1.6")
```

**Comment by lloydmeta** [comment]
Wait, I just realised that the readme says `// if you use coursier, you must use sbt-scalafmt-coursier`. I guess I should add `coursier` _as well as_ the `sbt-scalafmt-coursier` plugin?

**Comment by jvican** [comment]
Yes @lloydmeta, that's the idea.

**Comment by lloydmeta** [comment]
@jvican ok that makes sense. I'll close this issue now.
