### ISSUE TITLE
Warning: Unknown Scalafmt version 1.1.0; using 1.0 interface

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#35]
I believe Olaf confirmed that the 1.x line is going to be API compatible so perhaps this warning is overzealous?

**Comment by olafurpg** [comment]
I haven't setup MiMa yet but it will definitely be up before I do any public facing changes. 1.x series will be binary compatible with each other.

**Comment by joeycozza** [comment]
should be fixed with https://github.com/lucidsoftware/neo-sbt-scalafmt/commit/895361b0ba947d452d48e994eb2a71c0b6b0e450  

will close this issue once we cut a release.

**Comment by freeman42x** [comment]
Would need a fix for `Warning: Unknown Scalafmt version 1.2.0; using 1.0 interface also`
SBT project is printing a lot of those warnings on build

**Comment by ArturGajowy** [comment]
> Would need a fix for Warning: Unknown Scalafmt version 1.2.0; using 1.0 interface

Same here! :)
