### ISSUE TITLE
Support scalafmt 1.0.0-RC1

### ISSUE THREAD

**Issue by hseeberger** [lucidsoftware/neo-sbt-scalafmt#4]

**Comment by jeantil** [comment]
I just configured a project to use this plugin. Adding
```
 scalafmtVersion := "1.0.0-RC1"
```

to my build.sbt seemed to work just fine...

**Comment by hseeberger** [comment]
OK, I should be more specific: I can run `scalafmt` and that works, i.e. does (re)format files. But when I change a file and mess up the formatting, then run `compile`, no (re)formatting happens.

**Comment by jeantil** [comment]
oh ok, but that fails on 0.13.x too => #2

**Comment by pauldraper** [comment]
#2 fixed
