### ISSUE TITLE
Plugin with Scala 2.11 and scalafmt 1.1.0 cause NoSuchMethodError

### ISSUE THREAD

**Issue by dragisak** [lucidsoftware/neo-sbt-scalafmt#42]
We use Scala 2.11.11
plugins.sbt:
```scala
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")
```
build.sbt
```scala
scalafmtVersion in ThisBuild := "1.1.0"
```

`sbt scalafmt` throws
```
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at scala.meta.inputs.Input$String.<init>(Input.scala:23)
	at scala.meta.inputs.Input$String$.apply(Input.scala:23)
	at org.scalafmt.config.Config$.fromHoconString(Config.scala:55)
	at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:11)
	at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:9)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$18.apply(ScalafmtCorePlugin.scala:143)
	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$anonfun$18.apply(ScalafmtCorePlugin.scala:134)
...
```

My guess is that this is because `scalafmt-impl` 1.10-1.0 has not been published for Scala 2.11 so it tries to use `scalafmt-impl_2.12` in a Scala 2.11 project.

**Comment by mdedetrich** [comment]
I think I am getting a similar issue

```
[error] (logisticsCommonClientsTest/compile:scalafmt::scalafmtter) java.util.NoSuchElementException: Either.right.value on Left
root/compile:scalafmt
[error] java.util.NoSuchElementException: Either.right.value on Left
[error]         at scala.util.Either$RightProjection.get(Either.scala:453)
[error]         at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:11)
[error]         at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:9)
[error]         at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtCoreSettings$26(ScalafmtCorePlugin.scala:143)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)

```

**Comment by puneetar** [comment]
@mdedetrich  I was able to solve `Either.right.value on Left` by removing `afterImplicitKWInVerticalMultiline = true` from the scalafmt config.

**Comment by puneetar** [comment]
@dragisak I was able to resolve that error by removing `scalafmtVersion :=  "1.0.0-RC4"` from the  build.sbt. I am not sure about the reason though.

**Comment by mdedetrich** [comment]
@dragisak I also solved the error by manually specifying the  `scalafmtVersion`, maybe the default value for the version is a bit off?

**Comment by dragisak** [comment]
@puneetar How did you manage to use Scalafmt 1.1.0 or higher then ?

**Comment by dragisak** [comment]
@mdedetrich If you read the description, you'll see that I did specify `scalafmtVersion`. This issue is about trying to use `sbt-scalafmt` with `scalafmt` 1.1.0 or higher and Scala 2.11

**Comment by puneetar** [comment]
@dragisak, yes I am using 1.1.0 with scala 2.11

**Comment by pauldraper** [comment]
The error likely is a scalafmt config parse error (e.g. an option that isn't present in the version being used).

Since a415289d12d12bba9f0166291c5bbebc0b34156d, the error message has been fixed.
