### ISSUE TITLE
Release for sbt-1.0.0

### ISSUE THREAD

**Issue by snadorp** [lucidsoftware/neo-sbt-scalafmt#43]
Would be great to have a release build for the latest sbt release.

**Comment by thiloplanz** [comment]
I use this one with sbt 1.0:

`addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.10")`

Seems to work so far.

**Comment by jvican** [comment]
Should be closed. There's already a release for sbt 1.0.0.
