### ISSUE TITLE
Sometimes files are chopped at some random point

### ISSUE THREAD

**Issue by drewhk** [lucidsoftware/neo-sbt-scalafmt#45]
I guess somewhere a `close()` call or `flush()` call is missing as the plugin spuriously cuts the second half of a file at seemingly random positions. It is non-deterministic, i.e. it sometimes does not happen, but after a clean build it happens often enough to be problematic. I guess it just happens to work on Linux/Mac but Windows' file buffering strategy is likely different and suffers more from forgetting to properly flush.

**Comment by sirthias** [comment]
This is pretty bad!
Leaving files open is a major bug!
Not just that it can cause the formatter to "not work", it even entails a risk for true data loss.
Therefore I'd vote for classifying this ticket as "high-priority".

**Comment by eed3si9n** [comment]
Is this a problem with the plugin or Scalafmt proper? /cc @olafurpg

**Comment by drewhk** [comment]
Well, now I am not sure exactly which plugin causing the issue, I will try to track down fully tomorrow.

**Comment by olafurpg** [comment]
I think neo uses IO.write from sbt https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/3d5c1a2a9737bb775e44f2797a03c4eda7e6e3d2/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L134 scalafmt-core does not do IO

**Comment by drewhk** [comment]
It seems like sbt-header 3.0.0 is the real culprit (earlier version works fine), so this ticket can be safely ignored.
