### ISSUE TITLE
trigger ScalafmtCorePlugin

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#5]
It would be good if `ScalafmtCorePlugin` autoloaded. Doing this manually is a real pain on larger projects.

**Comment by pauldraper** [comment]
Agreed. It's an equally big pain to disable on larger projects, but enabled is a better default.

The worst that over-enabling does is add on some stuff to `update`.

**Comment by pauldraper** [comment]
ScalafmtPlugin and ScalafmtCorePlugin are now triggered automatically in sbt-scalafmt 1.0.

I disabled scalafmtOnCompile by default, though enabling it globally is trivially easy.

**Comment by fommil** [comment]
Awesome
