### ISSUE TITLE
Unhelpful error message when the configuration file is incorrect

### ISSUE THREAD

**Issue by nrinaudo** [lucidsoftware/neo-sbt-scalafmt#50]
I blame [this line](https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/e79e0fc76c8d6416b891f23597ce4c7528bed5e1/scalafmt-impl/src/scalafmt-0.6/main/scala/com/lucidchart/scalafmt/impl/ScalafmtFactory.scala#L11).

If you're going to throw an exception, it'd be better to forward the actual error message - `Either.right.get on Left` is confusing :)

**Comment by aeons** [comment]
Anything `.get` is not good though :)

**Comment by nrinaudo** [comment]
Oh agreed, I'm advocating for removal of `.get`.
Ideally, errors wouldn't be dealt with as exceptions, although I suppose within the scope of an SBT plugin it might be ok, since they'll bubble up to the SBT shell anyway.

But if exceptions are used, succeed on `Right` and manually throw an exception with a custom message on `Left`?

**Comment by aeons** [comment]
Yes, that makes sense to me, since we can't really recover from a bad config.
