### ISSUE TITLE
compilation performance bottleneck

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#54]
I have disabled `formatOnCompile`, yet if I do a no-op `compile` of my project in a warmed up sbt, this is the bottleneck (backtraces) in CSV format (taking around 20 seconds across all projects / test configs)

Is anybody able to confirm?

```
"Reverse Call Tree","Time (ms)","Level"
"com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(String) ScalafmtFactory.scala","76016","1"
"com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(String) ScalafmtFactory.scala:9","","2"
"com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtCoreSettings$26(Tuple4) ScalafmtCorePlugin.scala:154","","3"
"com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$$Lambda$4957.apply(Object)","","4"
"scala.Function1$$Lambda$610.apply(Object)","","5"
"sbt.internal.util.$tilde$greater.$anonfun$$u2219$1($tilde$greater, Function1, Predef$$less$colon$less, Object) TypeFunctions.scala:42","","6"
"sbt.internal.util.$tilde$greater$$Lambda$2274.apply(Object)","","7"
"sbt.std.Transform$$anon$4.work(Object) System.scala:64","","8"
"sbt.Execute.$anonfun$submit$2(Node, Object) Execute.scala:257","","9"
"sbt.Execute$$Lambda$2291.apply()","","10"
"sbt.internal.util.ErrorHandling$.wideConvert(Function0) ErrorHandling.scala:16","","11"
"sbt.Execute.work(Object, Function0, CompletionService) Execute.scala:266","","12"
"sbt.Execute.$anonfun$submit$1(Execute, Object, CompletionService, Node, Object) Execute.scala:257","","13"
"sbt.Execute$$Lambda$2282.apply()","","14"
"sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions$$anon$4, Object, Function0) ConcurrentRestrictions.scala:167","","15"
"sbt.ConcurrentRestrictions$$anon$4$$Lambda$2289.apply()","","16"
"sbt.CompletionService$$anon$2.call() CompletionService.scala:32","","17"
"java.lang.Thread.run() Thread.java:748","","18"
```

**Comment by fommil** [comment]
It seems that perhaps the result of this method should be cached in the sbt layer?

**Comment by fommil** [comment]
btw, I confirm that removing this plugin from my project means that no-op compile is 5 seconds.

**Comment by jvican** [comment]
Oh wow, so this was the culprit. Weird.

**Comment by fommil** [comment]
it would be great if somebody could help me with this... I don't know what the fix would be. Maybe passing around a lazy thing that only gets instantiated when required? Or caching the instances?

**Comment by jvican** [comment]
I think caching that method (if possible) is the way to go. I cannot add much more to this discussion; I don't have experience with this library. Maybe someone can have a look at this in our next Scala Center spree at Lambda World if you don't have time to open a PR.

**Comment by fommil** [comment]
@jvican that'd be truly awesome, and I don't think it'd be too hard. Either cache it or only create on demand (by-name parameters may help)

**Comment by leonardehrenfried** [comment]
Seems pretty trivial to add a cache here: https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/master/scalafmt-impl/src/scalafmt-1.0/main/scala/com/lucidchart/scalafmt/impl/ScalafmtFactory.scala#L11

Does sbt have some general purpose cache implementation that could be used? Or maybe Guava is already depended on - its CacheBuilder is pretty comprehensive if a little untyped.

**Comment by jvican** [comment]
Yes, sbt has a `Cache` implementation. Have a look at `util-cache` in https://github.com/sbt/util/tree/1.x/util-cache/src/main/scala/sbt/util.

**Comment by leonardehrenfried** [comment]
https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/56

**Comment by fommil** [comment]
![you're my hero](https://media1.tenor.com/images/396460a8255e020f0d22f186051018a8/tenor.gif?itemid=7441740)
