### ISSUE TITLE
performance: make scalafmt an actual dependency

### ISSUE THREAD

**Issue by fommil** [lucidsoftware/neo-sbt-scalafmt#58]
the caching is a good improvement but I wonder if it is perhaps applied at too high a level... would it make sense to cache the classpath instance of scalafmt so that the same classpath is reused between all the projects/configs? I'm assuming scalafmt is thread safe.

**Comment by pauldraper** [comment]
Good question. Just to check....

Then there's `com.lucidchart.scalafmt.api.ScalafmtFactory` which has `fromConfig(java.lang.String)` which parses config and produces a `com.lucidchart.scalafmt.Scalafmtter` which has `includeFile(java.nio.file.Path) and formatter(com.lucidchart.scalafmt.api.Dialect)`. The `formatter` method applies the dialect to the existing config as appropriate, and calls the static `org.scalafmt.Scalafmt.format(java.lang.String, org.scalafmt.config.ScalafmtConfig)`

We cache down to the `com.lucidchart.scalafmt.Scalafmtter` level. Copying the config with the appropriate dialect is the only extra repeat work being done before getting down the the scalafmt API.

**Comment by fommil** [comment]
We created a skeleton project for Lightbend to see perf regression in sbt 1.0... but it is also a really good demonstration of how scalafmt slows down the build on a project with no source code

  https://github.com/cakesolutions/sbt-cake/tree/sbt-perf-regression

i.e. typing `sbt cpl` (an alias to compile all configurations) incurs a constant overhead from scalafmt. The recent caching helps but it seems there is something else amiss.

**Comment by fommil** [comment]
also, starting `sbt` and then typing `fmt` is extremely slow... and there aren't even any sources in this project.

Perhaps it is time to make scalafmt a classpath dependency of this plugin? The classloader hack is a workaround for the 0.13 days.

**Comment by fommil** [comment]
if made a first class dependency in sbt 1.0, the scalafmt version flag would no longer make sense for sbt 1.0. Therefore that flag should be isolated to the 0.13 build and the latest stable of scalafmt should be used by default.

`build.sbt` will have to do some sbt version based switching to only add the correct deps for sbt 1.0, and probably the shared codebase between 0.13 and 1.0 will reduce to just the keys and common tasks like format on compile.
