### ISSUE TITLE
Please include license information

### ISSUE THREAD

**Issue by lutzh** [lucidsoftware/neo-sbt-scalafmt#62]
I can't seem to find any information on the license - no license file, no information in the readme, no license headers in the source files..

Please provide information regarding the license under which your code can be used / modified / distributed... thanks.

**Comment by pauldraper** [comment]
Thanks.

The Maven artifacts list Apache 2.

https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/1.15/build.sbt#L16
http://repo1.maven.org/maven2/com/lucidchart/sbt-scalafmt_2.10_0.13/1.15/sbt-scalafmt-1.15.pom

I added the license to git repo.
