### ISSUE TITLE
Unpublished from Maven Central?

### ISSUE THREAD

**Issue by mistadikay** [lucidsoftware/neo-sbt-scalafmt#67]
Facing this error while trying to install the latest version:
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lucidchart#sbt-scalafmt;1.15: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lucidchart:sbt-scalafmt:1.15
````

Maven Central shows versions from 1.6 to 1.15 https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.lucidchart%22%20AND%20a%3A%22sbt-scalafmt%22

However, repositories return 404, for example: http://repo1.maven.org/maven2/com/lucidchart/sbt-scalafmt/1.15/

**Comment by pauldraper** [comment]
It's there.

http://repo1.maven.org/maven2/com/lucidchart/sbt-scalafmt_2.10_0.13/1.15/
http://repo1.maven.org/maven2/com/lucidchart/sbt-scalafmt_2.12_1.0/1.15/'

Perhaps you installed it wrong (are you using addSbtPlugin?).

**Comment by mistadikay** [comment]
My bad, I added `addSbtPlugin` to `build.sbt` instead of `project/plugins.sbt`
