### ISSUE TITLE
Unable to format file due to bug in scalafmt should fail task

### ISSUE THREAD

**Issue by krzkaczor** [lucidsoftware/neo-sbt-scalafmt#7]
I am getting "Unable to format file due to bug in scalafmt" from scalafmt but it's considered as warning and whole sbt task exits successfully:
```
[warn] Unable to format file due to bug in scalafmt
[success] Total time: 4 s, completed Jun 4, 2017 6:59:35 PM
```

adding `-Xfatal-warnings` doesnt help

Repro for error here: https://github.com/scalameta/scalafmt/issues/965

**Comment by pauldraper** [comment]
scalafmt hasn't (yet) had a stable 1.0 release, and I've gotten a couple failures, e.g. using non-ASCII(?) characters in xml literals.

Added `ignoreErrors in scalafmt` setting to fail scalafmt tasks when these things happen.
